version: '3'
volumes:
  pgdatasource:
  
services:
  zprefix-db:
    image: postgres
    container_name: zprefix-db
    restart: always
    environment: 
     - DATABASE_HOST=127.0.0.1
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_PORT=5432
     - POSTGRES_DB=zprefix
    ports:
     - '5432:5432'
    networks:
      - app-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  zprefix-api:
    build: ./api
    container_name: zprefix-api
    depends_on:
      zprefix-db:
        condition: service_healthy
    ports:
      - '8082:8082'
    networks:
      - app-network
    environment: 
      - NODE_ENV=development
      - DATABASE_HOST=zprefix-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=zprefix
    volumes:
      - type: bind
        source: ./api
        target: /app
    command: npm run start:dev

  zprefix-ui:
    build: ./ui
    container_name: zprefix-ui
    environment:
      - FAST_REFRESH=false
    depends_on:
      - 'zprefix-api'
    ports:
      - '3001:3000'
    networks:
      - app-network
    volumes:
      - type: bind
        source: ./ui
        target: /app
  
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    depends_on:
      - zprefix-api
    ports:
      - '8080:8080'
    networks:
      - app-network
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=zprefix-db
      - DB_DATABASE=zprefix
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_SCHEMA=public
      - DB_PASSWORD=docker
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

networks:
  app-network:
    driver: bridge